### ISSUE TITLE
[Dev Branch] Remove onLoadName from description.ext

### ISSUE THREAD

**Issue by thepaullee** [CombinedArmsGaming/F3_CA#77]
Remove onLoadName from description.ext and make MMs use the (Attributes > General) in-editor Title field. This way CA_missionIntro can show a real name and MMs dont have to write the title twice

**Comment by Poulern** [comment]
The issue I've found with this is that if you have multiple versions uploaded, then they will all show with eg 
Operation Melkeku 
Operation Melkeku 
Operation Melkeku 
Operation Melkeku 

Instead of
ca_Khaki_co40_Op_Melkeku_v1
ca_Khaki_co40_Op_Melkeku_v2
ca_Khaki_co40_Op_Melkeku_v3
ca_Khaki_co40_Op_Melkeku_v4

Which if you're in a hurry can lead to the wrong mission getting loaded on the server for the event.

**Comment by thepaullee** [comment]
Ah alright, I've had some weird behaviour trying to use briefingName as well as sometimes it uses the file name anyway 

I think the best solution is just to do some quick string splicing since we always follow the same file naming convention, will make a PR
